openai-service:
  api-key: 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
  #  gpt-model: gpt-3.5-turbo
  gpt-model: gpt-3.5-turbo
  #  gpt-model: text-davinci-003
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    chat-url: https://api.openai.com/v1/chat/completions
    create-transcription-url: https://api.openai.com/v1/audio/transcriptions
    model-url: https://api.openai.com/v1/models
  file-name: Z:\翻译\Indiana Jones and the Dial of Destiny - Spoilers, STUPIDEST Moments & PLOT HOLES\识别1.srt
  #缺失行数起点-1
  start-index: 520
